name: Run Tests with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      ENVIRONMENT: local

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Wait for backend service to be ready
        run: |
          docker-compose exec backend bash -c "until curl --silent --fail http://localhost:5050; do echo waiting for app; sleep 5; done"

      - name: Run tests in backend container
        run: |
          docker-compose exec backend bash -c "pytest --maxfail=1 --disable-warnings"

      - name: Shutdown Docker Compose
        run: |
          docker-compose down
