name: Run Tests with Docker

on:
  push:
    branches:
      - main
jobs:
  backend-tests:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      ENVIRONMENT: pipeline
      PORT: 5050

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers with Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Wait for backend to be healthy
        run: |
          docker compose -f docker-compose.yml wait backend

      - name: Run tests in backend container
        run: |
          docker compose -f docker-compose.yml exec backend pytest

      - name: Display container logs if tests fail
        if: failure()
        run: |
          docker compose -f docker-compose.yml logs

      - name: Shutdown Docker Compose
        run: |
          docker compose down
