name: Run Tests with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      ENVIRONMENT: local
      PORT: 5050

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers with Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend service to be healthy..."
          until [ "$(docker compose ps -q backend)" ] && \
                [ "$(docker inspect -f '{{.State.Health.Status}}' $(docker compose ps -q backend))" == "healthy" ]; do
            echo "Backend is not ready yet. Waiting..."
            sleep 5
          done
          echo "Backend is healthy and ready to proceed."

      - name: Run tests in backend container
        run: |
          docker compose exec backend bash -c "pytest --maxfail=1 --disable-warnings"

      - name: Display container logs if tests fail
        if: failure()
        run: |
          docker compose -f docker-compose.yml logs

      - name: Shutdown Docker Compose
        run: |
          docker compose down
