name: Run Tests with Docker

on:
  push:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests in backend container
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ENVIRONMENT: local
          PORT: 5050
        run: |
          docker compose -f docker-compose.yml exec backend pytest

      - name: Display container logs if tests fail
        if: failure()
        run: |
          docker compose -f docker-compose.yml logs

      - name: Shutdown Docker Compose
        run: |
          docker compose down
