name: Run Tests with Docker

on:
  push:
    branches:
      - main
jobs:
  backend-tests:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      ENVIRONMENT: pipeline
      PORT: 5050

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers with Docker Compose
        run: |
          docker compose -f testing.yml up -d

      - name: Wait for backend to be healthy
        run: |
          timeout 60s docker compose -f testing.yml wait backend || echo "Timeout reached; continuing..."

      - name: Run tests with coverage in the backend container
        run: |
          docker compose -f testing.yml exec backend pytest --cov=/app --cov-report=xml:/app/coverage.xml

      - name: Display container logs if tests fail
        if: failure()
        run: |
          docker compose -f testing.yml logs

      - name: Upload coverage to GitHub Actions (optional)
        uses: codecov/codecov-action@v3
        with:
          file: /app/coverage.xml
        if: success()

      - name: Shutdown Docker Compose
        run: |
          docker compose down
