name: Run Tests with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers with Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Run tests in backend container
        run: |
          docker compose exec backend bash -c "pytest --maxfail=1 --disable-warnings"

      - name: Display container logs if tests fail
        if: failure()
        run: |
          docker compose -f docker-compose.yaml logs

      - name: Shutdown Docker Compose
        run: |
          docker compose down
